version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node

  asterisk:
    image: andrius/asterisk:latest
    container_name: asterisk
    restart: unless-stopped
    command: asterisk -f
    ports:
      - "5060:5060/udp"
      - "5038:5038"
      - "5060:5060/tcp"
      - "8088:8088/tcp"
      - "10000-10050:10000-10050/udp"
    volumes:
      - ./asterisk-config:/etc/asterisk
      - ./asterisk-sounds:/var/lib/asterisk/sounds
      - /etc/letsencrypt:/etc/letsencrypt:ro

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: potsbox-node
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3600:3600"
    volumes:
      - ./asterisk-sounds:/app/asterisk-sounds
    depends_on:
      - asterisk
    env_file:
      - .env
