services:
  asterisk:
    image: andrius/asterisk:latest
    container_name: asterisk
    restart: unless-stopped
    command: asterisk -f
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "8088:8088/tcp"
      - "10000-10050:10000-10050/udp"  # RTP range
    volumes:
      - ./asterisk-config:/etc/asterisk
      - ./asterisk-sounds:/var/lib/asterisk/sounds
